1.添加仓库拥有者点击star运行 2.添加curl必应并上传以避免GitHub Workflow被停用
CokeMine/EUserv_extend pull request #6
Opened 2020-12-03 13:30 UTC by sprindjack

2020-12-03 16:41 UTC, CokeMine requested changes
Hi,我觉得可以新建一个workflows的yaml文件，定时在每月某一天自动push
这样每月一次运行足够防止被停用了，也不会产生过多无关的commit和bot push的邮件

2020-12-04 00:06 UTC, sprindjack commented
是的，每个月运行一次更环保。

2020-12-04 00:06 UTC, closed without merging

2020-12-04 00:19 UTC, CokeMine commented
而且我觉得没有必要去curl一下bing，直接随机生成随机的uuid echo $(cat /proc/sys/kernel/random/uuid) > uuid.txt 然后再push就好。。如果curl bing的话，会导致Github判断整体项目的语言为HTML导致不准确。。

2020-12-04 01:40 UTC, sprindjack commented
呃，菜鸟一个，curl到bing是想到每天都有随机图。😂其他方式我不会用。

2020-12-04 01:57 UTC, CokeMine commented
> 呃，菜鸟一个，curl到bing是想到每天都有随机图。其他方式我不会用。

把
```bash
curl -o bing.html "https://www.bing.com"
```
换成
```bash
echo $(cat /proc/sys/kernel/random/uuid) > UUID.txt
```
就好啦，别的都不用动了

2020-12-04 02:01 UTC, sprindjack commented
> > 呃，菜鸟一个，curl到bing是想到每天都有随机图。其他方式我不会用。
> 
> 把
> 
> ```shell
> curl -o bing.html "https://www.bing.com"
> ```
> 
> 换成
> 
> ```shell
> echo $(cat /proc/sys/kernel/random/uuid) > UUID.txt
> ```
> 
> 就好啦，别的都不用动了

好的，已替换。谢谢大佬。